In [1]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
import torchvision

In [5]:
import matplotlib.pyplot as plt
from pprint import pprint
import numpy as np

from IPython.core.debugger import set_trace

%matplotlib inline

In [13]:
from ppt.utils import attr

ModuleNotFoundError: No module named 'ppt'

# Tensors

tensors - the atoms of machine learning

## Tensors in numpy and pytorch

In [16]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot

In [17]:
import torch

In [18]:
# numpy
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# torch
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [21]:
# numpy 
X = np.random.random((5, 3))
X

array([[0.00996835, 0.85328493, 0.68599486],
       [0.31728902, 0.25784696, 0.77824181],
       [0.03496852, 0.8673311 , 0.55543008],
       [0.86219195, 0.72785656, 0.47511191],
       [0.30002978, 0.92705051, 0.90530102]])

In [24]:
# pytorch 
Y = torch.rand(5,3)
Y

tensor([[0.9802, 0.3457, 0.8878],
        [0.7669, 0.9900, 0.5393],
        [0.4500, 0.6697, 0.2189],
        [0.2657, 0.7698, 0.7907],
        [0.4149, 0.6804, 0.1493]])

In [27]:
X.shape

(5, 3)

In [28]:
Y.shape

torch.Size([5, 3])

In [29]:
# numpy
X.T @ X

array([[0.93538731, 1.02634196, 0.95444331],
       [1.02634196, 2.93604129, 2.45283125],
       [0.95444331, 2.45283125, 2.43005312]])

In [30]:
# torch 
Y.t() @ Y

tensor([[1.9941, 1.8863, 1.6544],
        [1.8863, 2.6036, 1.6977],
        [1.6544, 1.6977, 1.7745]])

In [33]:
# numpy 
inv(X.T @ X)

array([[ 1.81191283, -0.24784717, -0.46148818],
       [-0.24784717,  2.20678381, -2.13012307],
       [-0.46148818, -2.13012307,  2.74286051]])

In [44]:
# torch
torch.inverse(Y.t() @ Y)

tensor([[ 2.7960, -0.8663, -1.7779],
        [-0.8663,  1.2895, -0.4260],
        [-1.7779, -0.4260,  2.6287]])

## More on Pytorch Tensors

Operations are also available as methods.

In [47]:
A = torch.eye(3)
A.add(1)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [48]:
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Any operation that mutates a tensor in-place is post-fixed with an. For example: x.copy(y), x.t_(). will change x. 

In [60]:
A.add_(1)
A

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

## Indexing and broadcasting

It works as expected:

In [61]:
A

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [63]:
A[0,0]

tensor(2.)

In [64]:
A[0]

tensor([2., 1., 1.])

In [65]:
A[0:2]

tensor([[2., 1., 1.],
        [1., 2., 1.]])

In [67]:
A[:, 1:3]

tensor([[1., 1.],
        [2., 1.],
        [1., 2.]])

## Converting

In [68]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [69]:
# torch --> numpy
A.numpy()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [70]:
# numpy --> torch 
torch.from_numpy(np.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)

## Autograd

Prior to v0.4 PyTorch used the class Variable to record gradients. Your had to wrap Tensors in Variables. Variables behaved like Tensors. With v.0.4 Tensor can record gradients directly if you tell it to do so, e.g. torch.ones(3, requires_grad=True). There is no need for Variable anymore. 

Ref: 

- https://pytorch.org/docs/stable/autograd.html
- https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

In [71]:
from torch import autograd # you rarely use it directly

In [73]:
w = torch.ones(1)
w.requires_grad

False

In [74]:
z = torch.ones(1) * 2
z.requires_grad

False

In [75]:
total = w + z
total

tensor([3.])

In [77]:
# What is goind to happen here?
total.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [78]:
w = torch.ones(1, requires_grad=True)
w.requires_grad

True

In [79]:
total = w + z
total.requires_grad

True

In [80]:
total.backward()

/home/jakobwaibel/anaconda3/lib/python3.8/site-packages/torch/autograd/__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729062494/work/c10/cuda/CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


In [81]:
w.grad

tensor([1.])